"""Create blackliststed_tokens table.

Revision ID: 71663fc02fff
Revises: b8fc3a1bbc2a
Create Date: 2024-08-13 12:26:47.057014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71663fc02fff'
down_revision = 'b8fc3a1bbc2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###
